# docker-compose.ymlファイルのフォーマットのバージョンを指定
version: '3'
# services下にコンテナで作られるサービスを定義
services:
  app:
    build: .
    # (左)ホストマシンのディレクトリを(右)コンテナのディレクトリにマウント
    volumes:
    - ./:/go/src/qiita-bot
    # 公開するportを指定 (左 ホストマシンのポート, 右 コンテナのポート)
    ports:
    - "8100:8100"
